name: Postman API Tests

on:
  push:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        env:
          POSTMAN_TOKEN: ${{ secrets.TOKEN_POSTMAN }}
        run: |
          newman run "GitHub API Testing.postman_collection.json" \
            -e "GitHub.postman_environment.json" \
            --env-var "token=$POSTMAN_TOKEN"